#!/usr/bin/env python3
"""
Compare left-hemisphere peripheral SRPK1-associated cortical MSN maps with the MDD-related cortical MSN map using spatial null models.

Set MSN_PROJECT_ROOT to the project data directory before running.
"""

import warnings
warnings.filterwarnings("ignore")

import json
import re
import numpy as np
import pandas as pd
from pathlib import Path
import os
from scipy.stats import zscore
from neuromaps import stats


# =========================
# user configuration
# =========================
# Set this environment variable to the root directory containing the input data.
# Example: export MSN_PROJECT_ROOT=/path/to/msn_2026
PROJECT_ROOT = Path(os.environ.get("MSN_PROJECT_ROOT", "/path/to/msn_2026")).expanduser()


# =========================
# input and output paths
# =========================
srpk1_dir = PROJECT_ROOT / "msn_results_cort/srpk1_msn_assoc_v2"

disease_model_tag = "mdd_hc_covariates"
disease_map_file = PROJECT_ROOT / "msn_results_cort/tmap_mdd_vs_hc_covariates.csv"

roi_order_file = PROJECT_ROOT / "dk308_roi_order.txt"

# SRPK1 maps generated by step5_SRPK1_related_cort_map_v2.R
# main is the batch-adjusted primary model:
# y ~ SRPK1 + Batch + age + sex + EDL + eTIV
srpk1_maps = {
    "batch_main": srpk1_dir / "srpk1_imaging_map_main.csv",
    "batch_plus_med_history": srpk1_dir / "srpk1_imaging_map_plus_med_history.csv",
    "batch_plus_neutrophils": srpk1_dir / "srpk1_imaging_map_plus_neutrophils.csv",
    "batch_plus_med_history_neutrophils": srpk1_dir / "srpk1_imaging_map_plus_med_history_neutrophils.csv",
}

# LEFT hemisphere Burt nulls for DK-308
burt_null_file = PROJECT_ROOT / "burt2020_dk308_lh_perm10000_2mm.npy"

out_dir = PROJECT_ROOT / "msn_results_cort/a2_srpk1_vs_disease_batch_lh"
out_dir.mkdir(parents=True, exist_ok=True)

result_file = out_dir / "a2_srpk1_vs_mdd_hc_batch_models_burt_results_lh_v1.csv"
meta_file = out_dir / "a2_srpk1_vs_mdd_hc_batch_models_meta_lh_v1.json"
roi_order_check_file = out_dir / "a2_dk308_lh_roi_order_check_v1.csv"


# =========================
# settings
# =========================
roi_col = "ROI"
srpk1_val_col = "t"
disease_val_col = "t_group_MDD"
expected_n_roi = 152
expected_full_n_roi = 308
expected_n_lh = 152
expected_n_rh = 156
use_zscore = False


# =========================
# helpers
# =========================
def check_file(path, label):
    if not path.exists():
        raise FileNotFoundError(f"{label} not found: {path}")


def normalize_roi_name(x):
    return str(x).strip().strip("'").strip('"')


def read_roi_order(path):
    check_file(path, "DK-308 ROI order file")
    text = path.read_text(encoding="utf-8", errors="ignore")

    names = re.findall(r"'([^']+)'", text)

    if len(names) == 0:
        names = []
        for line in text.splitlines():
            line = line.strip()
            if line == "" or line.lower() == "roi":
                continue
            parts = [p.strip() for p in line.split(",") if p.strip() != ""]
            names.extend(parts)

    names = [normalize_roi_name(x) for x in names if normalize_roi_name(x) != ""]

    if len(names) != expected_full_n_roi:
        raise ValueError(
            f"Expected {expected_full_n_roi} ROI names in ROI order file, got {len(names)}."
        )

    if len(set(names)) != expected_full_n_roi:
        s = pd.Series(names)
        dup = s[s.duplicated()].tolist()
        raise ValueError(f"Duplicated ROI names in ROI order file: {dup[:20]}")

    n_lh = sum(x.startswith("lh_") for x in names)
    n_rh = sum(x.startswith("rh_") for x in names)
    n_other = len(names) - n_lh - n_rh

    if n_lh != expected_n_lh or n_rh != expected_n_rh or n_other != 0:
        raise ValueError(
            f"Unexpected ROI order hemisphere counts: lh={n_lh}, rh={n_rh}, other={n_other}."
        )

    lh_names = [x for x in names if x.startswith("lh_")]
    if len(lh_names) != expected_n_roi:
        raise ValueError(f"Expected {expected_n_roi} LH ROI names, got {len(lh_names)}.")

    return names, lh_names


def prepare_map(path, value_col, value_name, label):
    check_file(path, label)
    df = pd.read_csv(path)
    df.columns = [str(x).strip() for x in df.columns]

    missing_cols = sorted(set([roi_col, value_col]) - set(df.columns))
    if missing_cols:
        raise ValueError(f"Missing columns in {label}: {missing_cols}")

    df = df[[roi_col, value_col]].rename(columns={value_col: value_name}).copy()
    df[roi_col] = df[roi_col].map(normalize_roi_name)
    df[value_name] = pd.to_numeric(df[value_name], errors="coerce")

    if len(df) not in [expected_n_roi, expected_full_n_roi]:
        raise ValueError(
            f"Expected {expected_n_roi} LH rows or {expected_full_n_roi} bilateral rows in {label}, got {len(df)}."
        )

    if df[roi_col].duplicated().any():
        dup = df.loc[df[roi_col].duplicated(), roi_col].tolist()
        raise ValueError(f"Duplicated ROI in {label}: {dup[:20]}")

    return df


def align_map_to_lh_order(df, value_name, lh_roi_order, label):
    target_set = set(lh_roi_order)
    input_set = set(df[roi_col])

    missing = [x for x in lh_roi_order if x not in input_set]
    extra = sorted(input_set - target_set)

    if len(missing) > 0:
        raise ValueError(f"LH ROI names missing in {label}: {missing[:30]}")

    lookup = pd.DataFrame({
        roi_col: lh_roi_order,
        "atlas_order": np.arange(1, len(lh_roi_order) + 1),
        "hemisphere": "lh",
    })

    aligned = lookup.merge(
        df[[roi_col, value_name]],
        on=roi_col,
        how="left",
        validate="one_to_one"
    )

    if aligned[value_name].isna().any():
        bad = aligned.loc[aligned[value_name].isna(), roi_col].tolist()
        raise ValueError(f"Missing numeric values after LH alignment in {label}: {bad[:30]}")

    n_lh = int((aligned["hemisphere"] == "lh").sum())
    n_rh = int((aligned["hemisphere"] == "rh").sum())

    if n_lh != expected_n_roi or n_rh != 0:
        raise ValueError(
            f"Unexpected hemisphere counts after LH alignment in {label}: lh={n_lh}, rh={n_rh}."
        )

    return aligned, extra


def maybe_zscore(x, y):
    if not use_zscore:
        return x, y

    x = zscore(x, nan_policy="omit")
    y = zscore(y, nan_policy="omit")
    x = np.nan_to_num(x, nan=0.0, posinf=0.0, neginf=0.0)
    y = np.nan_to_num(y, nan=0.0, posinf=0.0, neginf=0.0)
    return x, y


def load_lh_nulls(path, n_roi):
    check_file(path, "LH Burt null file")
    nulls = np.load(path)
    print("Null shape before check:", nulls.shape)

    if nulls.ndim != 2:
        raise ValueError(f"Expected a 2D null array, got shape {nulls.shape}.")

    if nulls.shape[0] != n_roi and nulls.shape[1] == n_roi:
        print("Transposing nulls to ROI x permutation format.")
        nulls = nulls.T

    if nulls.shape[0] != n_roi:
        raise ValueError(
            f"Null first dimension ({nulls.shape[0]}) does not match number of LH ROIs ({n_roi})."
        )

    print("Null shape after check:", nulls.shape)
    return nulls


# =========================
# read ROI order, fixed disease map and nulls
# =========================
full_roi_order, lh_roi_order = read_roi_order(roi_order_file)

roi_order_check = pd.DataFrame({
    "atlas_order": np.arange(1, expected_n_roi + 1),
    "ROI": lh_roi_order,
    "hemisphere": "lh",
})
roi_order_check.to_csv(roi_order_check_file, index=False)

disease_df_raw = prepare_map(
    disease_map_file,
    disease_val_col,
    "disease_t",
    "disease map"
)

disease_df, disease_extra = align_map_to_lh_order(
    disease_df_raw,
    "disease_t",
    lh_roi_order,
    "disease map"
)

print("Raw disease ROI count:", len(disease_df_raw))
print("Ignored extra disease ROIs outside LH order:", len(disease_extra))

nulls = load_lh_nulls(burt_null_file, expected_n_roi)


# =========================
# run all SRPK1 models
# =========================
all_results = []
meta = {
    "analysis": "cortical_a2_SRPK1_MSN_tmap_vs_MDD_HC_MSN_tmap_LH",
    "disease_model_tag": disease_model_tag,
    "disease_map_file": str(disease_map_file),
    "roi_order_file": str(roi_order_file),
    "roi_order_check_file": str(roi_order_check_file),
    "burt_null_file": str(burt_null_file),
    "expected_n_roi": expected_n_roi,
    "expected_full_n_roi": expected_full_n_roi,
    "expected_n_lh": expected_n_lh,
    "expected_n_rh": expected_n_rh,
    "use_zscore": use_zscore,
    "srpk1_maps": {k: str(v) for k, v in srpk1_maps.items()},
    "note": (
        "Bilateral input maps are read when available, but only LH ROIs from dk308_roi_order.txt "
        "are retained before extracting x/y vectors. This ensures x, y and the LH Burt nulls "
        "share the same ROI order. SRPK1 batch_main corresponds to "
        "y ~ SRPK1 + Batch + age + sex + EDL + eTIV."
    ),
}

for srpk1_model_tag, srpk1_map_file in srpk1_maps.items():
    print("\n==============================")
    print("Running SRPK1 model:", srpk1_model_tag)
    print("SRPK1 file:", srpk1_map_file)

    srpk1_df_raw = prepare_map(
        srpk1_map_file,
        srpk1_val_col,
        "srpk1_t",
        "SRPK1 map"
    )

    srpk1_df, srpk1_extra = align_map_to_lh_order(
        srpk1_df_raw,
        "srpk1_t",
        lh_roi_order,
        "SRPK1 map"
    )

    print("Raw SRPK1 ROI count:", len(srpk1_df_raw))
    print("Ignored extra SRPK1 ROIs outside LH order:", len(srpk1_extra))

    df = srpk1_df[[roi_col, "atlas_order", "hemisphere", "srpk1_t"]].merge(
        disease_df[[roi_col, "atlas_order", "hemisphere", "disease_t"]],
        on=[roi_col, "atlas_order", "hemisphere"],
        how="inner",
        validate="one_to_one"
    )

    print("Aligned merged LH ROI count:", len(df))
    print("Aligned first LH ROI:", df[roi_col].iloc[0])
    print("Aligned last LH ROI:", df[roi_col].iloc[-1])
    print(df.head())

    if len(df) != expected_n_roi:
        raise ValueError(
            f"Expected {expected_n_roi} LH ROIs after merge for {srpk1_model_tag}, got {len(df)}."
        )

    df = df.dropna(subset=["srpk1_t", "disease_t"]).copy()
    print("ROI count after dropna:", len(df))

    if len(df) != expected_n_roi:
        raise ValueError(
            f"ROI count after dropna is not {expected_n_roi} for {srpk1_model_tag}."
        )

    x_raw = df["srpk1_t"].to_numpy(dtype=float)
    y_raw = df["disease_t"].to_numpy(dtype=float)
    x, y = maybe_zscore(x_raw, y_raw)

    df["srpk1_t_used"] = x
    df["disease_t_used"] = y

    if nulls.shape[0] != len(df):
        raise ValueError(
            f"Null first dimension ({nulls.shape[0]}) does not match number of LH ROIs ({len(df)})."
        )

    merged_file = out_dir / f"a2_input_merged_maps_srpk1_{srpk1_model_tag}_vs_{disease_model_tag}_lh_v1.csv"
    null_corr_file = out_dir / f"a2_null_distribution_srpk1_{srpk1_model_tag}_vs_{disease_model_tag}_lh_v1.csv"
    df.to_csv(merged_file, index=False)

    r_obs, p_burt = stats.compare_images(x, y, nulls=nulls)
    r_naive = np.corrcoef(x, y)[0, 1]

    null_corrs = np.array(
        [np.corrcoef(nulls[:, i], y)[0, 1] for i in range(nulls.shape[1])],
        dtype=float,
    )
    pd.DataFrame({"null_r": null_corrs}).to_csv(null_corr_file, index=False)

    print(f"Observed r = {r_obs:.6f}")
    print(f"Burt-null p = {p_burt:.6f}")

    all_results.append({
        "comparison": "Peri_SRPK1_MSN_tmap_vs_MDD_HC_MSN_tmap_LH",
        "srpk1_model_tag": srpk1_model_tag,
        "disease_model_tag": disease_model_tag,
        "srpk1_map_file": str(srpk1_map_file),
        "disease_map_file": str(disease_map_file),
        "roi_order_file": str(roi_order_file),
        "n_roi": len(df),
        "n_lh": int((df["hemisphere"] == "lh").sum()),
        "n_rh": int((df["hemisphere"] == "rh").sum()),
        "n_srpk1_extra_ignored": len(srpk1_extra),
        "n_disease_extra_ignored": len(disease_extra),
        "aligned_first_roi": df[roi_col].iloc[0],
        "aligned_last_roi": df[roi_col].iloc[-1],
        "use_zscore": use_zscore,
        "r_obs": r_obs,
        "r_naive": r_naive,
        "p_burt": p_burt,
        "n_perm": nulls.shape[1],
        "null_mean": float(np.nanmean(null_corrs)),
        "null_sd": float(np.nanstd(null_corrs)),
        "null_min": float(np.nanmin(null_corrs)),
        "null_max": float(np.nanmax(null_corrs)),
        "merged_file": str(merged_file.name),
        "null_corr_file": str(null_corr_file.name),
    })

# =========================
# save summary
# =========================
result_df = pd.DataFrame(all_results)
result_df.to_csv(result_file, index=False)

with open(meta_file, "w") as f:
    json.dump(meta, f, indent=2)

print("\n==============================")
print("All done.")
print("Saved result summary to:", result_file)
print("Saved meta to:", meta_file)
print(result_df)
